services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      JAVA_TOOL_OPTIONS: "-Djdk.disableContainerMetrics=true"
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      JAVA_TOOL_OPTIONS: "-Djdk.disableContainerMetrics=true"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  clickhouse:
    image: clickhouse/clickhouse-server:24.3.3.102
    container_name: clickhouse
    depends_on:
      - kafka
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - clickhouse_data:/var/lib/clickhouse

  data-generator:
    build: ./data-generator
    container_name: data-generator
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: "kafka:29092"
      KAFKA_TOPIC: "spotify_tracks_events"
      DATASET_PATH: "/app/data/spotify_dataset_clear.csv"
      EVENT_DELAY_SEC: "0.01"
      LOOP_FOREVER: "false"
    volumes:
      - ./data/spotify_dataset_clear.csv:/app/data/spotify_dataset_clear.csv:ro

  metabase:
    build: ./metabase
    container_name: metabase
    depends_on:
      - clickhouse
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase.db/metabase.db
      MB_JETTY_PORT: 3000
      MB_PLUGINS_DIR: /plugins
    volumes:
      - metabase_data:/metabase.db

volumes:
  clickhouse_data:
  metabase_data:
